### PR TITLE
Allow recursive installation of gom files

### PR DESCRIPTION
**Pull request by SimonRichardson**

### CODE REVIEW

**Comment by hugecannon** [comment]
will this still install in _vendor/ or will it install to _vendor/src/github.com/user/project/_vendor/ ?

**Comment by SimonRichardson** [comment]
`_vendor/`

**Comment by hugecannon** [comment]
Looks good to me then :+1:

**Comment by hugecannon** [comment]
Though we need to ensure we're respecting GOM_VENDOR_NAME

**Comment by SimonRichardson** [comment]
Closing this as we now use glide.

**Pull request closed without merging**
